// <auto-generated />
namespace VeriErisimler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class authorpass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(authorpass));
        
        string IMigrationMetadata.Id
        {
            get { return "202203211132448_authorpass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
